# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KarteSDKPlugin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for KarteSDKPlugin
  pod 'KarteCore'
  pod 'KarteInAppMessaging'
  pod 'KarteRemoteNotification'
  pod 'KarteVariables'
end
